apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
spec:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 64Mi
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  port: 8080
  liveness:
    path: /healthz
  readiness:
    path: /healthz
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: HUNTER2_BIND_ADDRESS
      value: "0.0.0.0:8080"
    - name: HUNTER2_DEBUG
      value: "{{ .Values.debug }}"
    - name: HUNTER2_GOOGLE_PROJECT_ID
      value: {{ .Values.googleProjectID }}
    - name: HUNTER2_GOOGLE_PUBSUB_SUBSCRIPTION_NAME
      value: {{ .Values.pubsubSubscriptionName  }}
  accessPolicy:
    outbound:
      external:
        - host: secretmanager.googleapis.com
        - host: pubsub.googleapis.com
