apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-apiserver
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Egress
