@startuml component
title Hunter2 Sequence Flow
skinparam maxMessageSize 300
autonumber

actor developer as "Developer"
control hunter as "Hunter2"

box "Google Project Resources"
participant SecretManager
participant PubSub
end box

box "Team Cluster Resources"
participant Secret
participant Application
end box

loop forever
	hunter -> PubSub: watch for updates
end

==On create / update==

developer -> SecretManager: Add or update secret
SecretManager -> PubSub: Update
hunter -> Secret: is managed
hunter -> SecretManager: get secret

group secret do not exists in cluster
    hunter -> Secret: create
end

group secret already exists in cluster
    hunter -> Secret: update
end

group secret do not exists in SecretManager
    hunter -> Secret: delete
end

hunter -> PubSub: ack msg

==On deletion==
    developer -> SecretManager: delete
    SecretManager -> PubSub: Update
    hunter -> Secret: is managed
    hunter -> SecretManager: get secret

group secret do not exists in SecretManager
      hunter -> Secret: delete
end

==On Error==
hunter -> Secret: is managed
hunter -> SecretManager: get secret

group unhandled error
    hunter -> hunter: return without acking
end

== Usage Hunter2 ==

Secret -> Application: mount

@enduml
