@startuml component
title Hunter2 Sequence Flow
skinparam maxMessageSize 300
autonumber

actor developer as "Developer"

box "Google Project Resources"
participant SecretManager as "Secret Manager"
participant LogRouter as "Log Router"
participant PubSub as "PubSub Topic"
end box

box "Kubernetes Cluster Resources"
control hunter as "Hunter2"
participant Secret
end box

developer -> SecretManager: create secret / \ncreate secret version / \ndelete secret
SecretManager -> LogRouter: audit logs
LogRouter -> PubSub: publish filtered audit logs
hunter -> PubSub: subscribe to updates

== on new events ==

hunter -> Secret: check if exists
group secret already exists in cluster
  hunter -> Secret: check for specific annotation
  group annotation not found
    hunter -> PubSub: ack and return early
  end
end

hunter -> SecretManager: fetch secret metadata and data

group if secret not found in Secret Manager
  hunter -> Secret: delete
else else
  hunter -> Secret: create or update
end

hunter -> PubSub: ack message

@enduml
