name: Build and deploy hunter2

on: [push]

env:
  hunter2_image: docker.pkg.github.com/${{ github.repository }}/hunter2

jobs:
  build:
    name: Checkout code and setup node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate image environment variable
        shell: bash
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "HUNTER2_IMAGE=${hunter2_image}:${version}" >> $GITHUB_ENV
      - name: Build hunter2 docker image
        run: docker build . --tag $HUNTER2_IMAGE --tag ${hunter2_image}:latest
      - name: Login to Github package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$GITHUB_REPOSITORY" --password-stdin
      - name: Push docker image
        run: |
          docker push $HUNTER2_IMAGE
  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${hunter2_image}:${version}" >> $GITHUB_ENV
          echo "NAIS_YAML=${GITHUB_WORKSPACE}/nais-yaml" >> $GITHUB_ENV
          pwd
      - name: Bump version in nais-yaml
        env:
          DEPLOY_KEY: ${{ secrets.NAIS_YAML_DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          mkdir -p $NAIS_YAML
          git clone git@github.com:navikt/nais-yaml.git $NAIS_YAML
          cd $NAIS_YAML
          git config user.email "aura@nav.no"
          git config user.name "NAIS deploy pipeline"
          sed -E -i "s#hunter2_image: .+#hunter2_image: ${IMAGE}#" vars/teams.yaml
          git add .
          git --no-pager diff --cached
          git commit -a -m "Bump hunter2 to version ${version}"
          git push
