name: Build and deploy hunter2

on: [push]

env:
  image: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: Checkout code and setup node
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build an push the Docker image
        run: |
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}
  deploy:
    name: Deploy to Kubernetes
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: hunter2
      - uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ secrets.SRVNAIS_REPO_PUSH_PAT }}
          path: nais-yaml
      - name: Generate image environment variable
        run: |
          cd hunter2
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Bump version in nais-yaml
        run: |
          cd nais-yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sed -E -i "s#hunter2_image: .+#hunter2_image: ${IMAGE}#" vars/global.yaml
          git add .
          git --no-pager diff --cached
          git commit --no-verify -a -m "Bump hunter2 to version ${version}"
          git push
